services:
  demo-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductDB;User Id=sa;Password=Neenu!Pass22;TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Neenu!Pass22
    ports:
      - "1433:1433"